name: truevibes
description: "A Flutter app for creating apps on multiple platforms."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Added dependencies for the project list screen
  path_provider: ^2.1.1      # Accessing filesystem paths
  hive: ^2.2.3               # Lightweight and fast NoSQL database
  hive_flutter: ^1.1.0       # Flutter-specific Hive utilities
  intl: ^0.18.1              # For date formatting
  file_picker: ^6.0.0        # For picking directories for new projects
  provider: ^6.1.1           # For state management
  permission_handler: ^11.0.0  # For handling permissions

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1     # Code generation for Hive
  build_runner: ^2.4.6       # Runs code generators

flutter:
  uses-material-design: true
