name: Build TrueVibes

on:
  push:
    branches: [ main ]

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      build_idx: ${{ steps.set-build-info.outputs.build_idx }}
      build_date: ${{ steps.set-build-info.outputs.build_date }}
    steps:
      - name: Set Build Information
        id: set-build-info
        run: |
          echo "build_date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
          echo "build_idx=${{ github.run_number }}" >> $GITHUB_OUTPUT

  build-android:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.6.0'
          channel: 'stable'
      
      - name: Get dependencies
        run: flutter pub get
      
      - name: Update build.gradle with version
        run: |
          VERSION_NAME="${{ needs.setup.outputs.build_date }}.${{ needs.setup.outputs.build_idx }}"
          sed -i "s/versionName \"1.0.0\"/versionName \"$VERSION_NAME\"/" android/app/build.gradle
          sed -i "s/versionCode 1/versionCode ${{ github.run_number }}/" android/app/build.gradle
      
      - name: Build APK
        run: flutter build apk --release
      
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: truevibes-android-${{ needs.setup.outputs.build_date }}.${{ needs.setup.outputs.build_idx }}
          path: build/app/outputs/flutter-apk/app-release.apk

  build-ios:
    needs: setup
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.6.0'
          channel: 'stable'
      
      - name: Get dependencies
        run: flutter pub get
      
      - name: Update Info.plist with version
        run: |
          VERSION_NAME="${{ needs.setup.outputs.build_date }}.${{ needs.setup.outputs.build_idx }}"
          /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $VERSION_NAME" ios/Runner/Info.plist
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion ${{ github.run_number }}" ios/Runner/Info.plist
      
      - name: Build iOS
        run: flutter build ios --release --no-codesign
      
      - name: Create IPA
        run: |
          cd build/ios/iphoneos
          mkdir Payload
          cp -r Runner.app Payload
          zip -r truevibes-ios.ipa Payload
      
      - name: Upload IPA
        uses: actions/upload-artifact@v2
        with:
          name: truevibes-ios-${{ needs.setup.outputs.build_date }}.${{ needs.setup.outputs.build_idx }}
          path: build/ios/iphoneos/truevibes-ios.ipa

  build-macos:
    needs: setup
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.6.0'
          channel: 'stable'
      
      - name: Get dependencies
        run: flutter pub get
      
      - name: Update Info.plist with version
        run: |
          VERSION_NAME="${{ needs.setup.outputs.build_date }}.${{ needs.setup.outputs.build_idx }}"
          /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $VERSION_NAME" macos/Runner/Info.plist
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion ${{ github.run_number }}" macos/Runner/Info.plist
      
      - name: Build macOS
        run: flutter build macos --release
      
      - name: Create dmg
        run: |
          cd build/macos/Build/Products/Release
          mkdir -p TrueVibes
          cp -r truevibes.app TrueVibes/
          hdiutil create -volname "TrueVibes" -srcfolder TrueVibes -ov -format UDZO truevibes-macos.dmg
      
      - name: Upload dmg
        uses: actions/upload-artifact@v2
        with:
          name: truevibes-macos-${{ needs.setup.outputs.build_date }}.${{ needs.setup.outputs.build_idx }}
          path: build/macos/Build/Products/Release/truevibes-macos.dmg

  build-windows:
    needs: setup
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.6.0'
          channel: 'stable'
      
      - name: Get dependencies
        run: flutter pub get
      
      - name: Update Runner.rc with version
        shell: pwsh
        run: |
          $VERSION_NAME="${{ needs.setup.outputs.build_date }}.${{ needs.setup.outputs.build_idx }}"
          (Get-Content windows/runner/Runner.rc) -replace 'VERSION_AS_STRING "1.0.0"', "VERSION_AS_STRING `"$VERSION_NAME`"" | Set-Content windows/runner/Runner.rc
          (Get-Content windows/runner/Runner.rc) -replace 'VERSION_AS_NUMBER 1,0,0', "VERSION_AS_NUMBER ${{ github.run_number }},0,0" | Set-Content windows/runner/Runner.rc
      
      - name: Build Windows
        run: flutter build windows --release
      
      - name: Create installer
        shell: pwsh
        run: |
          Compress-Archive -Path build\windows\runner\Release\* -DestinationPath truevibes-windows.zip
      
      - name: Upload Zip
        uses: actions/upload-artifact@v2
        with:
          name: truevibes-windows-${{ needs.setup.outputs.build_date }}.${{ needs.setup.outputs.build_idx }}
          path: truevibes-windows.zip

  build-linux:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.6.0'
          channel: 'stable'
      
      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev
      
      - name: Get dependencies
        run: flutter pub get
      
      - name: Update CMakeLists.txt with version
        run: |
          VERSION_NAME="${{ needs.setup.outputs.build_date }}.${{ needs.setup.outputs.build_idx }}"
          sed -i "s/set(APPLICATION_VERSION \"1.0.0\")/set(APPLICATION_VERSION \"$VERSION_NAME\")/" linux/CMakeLists.txt
      
      - name: Build Linux
        run: flutter build linux --release
      
      - name: Create tarball
        run: |
          cd build/linux/x64/release
          tar -czvf truevibes-linux.tar.gz bundle
      
      - name: Upload tarball
        uses: actions/upload-artifact@v2
        with:
          name: truevibes-linux-${{ needs.setup.outputs.build_date }}.${{ needs.setup.outputs.build_idx }}
          path: build/linux/x64/release/truevibes-linux.tar.gz

  create-release:
    needs: [setup, build-android, build-ios, build-macos, build-windows, build-linux]
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ needs.setup.outputs.build_date }}.${{ needs.setup.outputs.build_idx }}
          release_name: Release ${{ needs.setup.outputs.build_date }}.${{ needs.setup.outputs.build_idx }}
          draft: false
          prerelease: false
      
      - name: Download all artifacts
        uses: actions/download-artifact@v2
        
      - name: Get artifact names
        id: get-artifact-names
        run: |
          echo "::set-output name=android::$(ls truevibes-android-*/*.apk)"
          echo "::set-output name=ios::$(ls truevibes-ios-*/*.ipa)"
          echo "::set-output name=macos::$(ls truevibes-macos-*/*.dmg)"
          echo "::set-output name=windows::$(ls truevibes-windows-*/*.zip)"
          echo "::set-output name=linux::$(ls truevibes-linux-*/*.tar.gz)"
      
      - name: Upload Android Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.get-artifact-names.outputs.android }}
          asset_name: truevibes-android-${{ needs.setup.outputs.build_date }}.${{ needs.setup.outputs.build_idx }}.apk
          asset_content_type: application/vnd.android.package-archive
      
      - name: Upload iOS Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.get-artifact-names.outputs.ios }}
          asset_name: truevibes-ios-${{ needs.setup.outputs.build_date }}.${{ needs.setup.outputs.build_idx }}.ipa
          asset_content_type: application/octet-stream
      
      - name: Upload macOS Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.get-artifact-names.outputs.macos }}
          asset_name: truevibes-macos-${{ needs.setup.outputs.build_date }}.${{ needs.setup.outputs.build_idx }}.dmg
          asset_content_type: application/x-apple-diskimage
      
      - name: Upload Windows Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.get-artifact-names.outputs.windows }}
          asset_name: truevibes-windows-${{ needs.setup.outputs.build_date }}.${{ needs.setup.outputs.build_idx }}.zip
          asset_content_type: application/zip
      
      - name: Upload Linux Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.get-artifact-names.outputs.linux }}
          asset_name: truevibes-linux-${{ needs.setup.outputs.build_date }}.${{ needs.setup.outputs.build_idx }}.tar.gz
          asset_content_type: application/gzip
